import type {
  GenerateRequest,
  GeneratedFile,
  GenerationResult,
  SchemaAnalysis,
  SchemaEntity,
  SwaggerEndpoint,
} from "@/types";
import { analyzeSchema } from "./analyze";

/* ─────────────────────────────────────────────────────────────
 * Deterministic mock generator.
 *
 * Produces a complete, coherent Express + TypeScript project
 * tailored to the entities extracted from the user's input, so
 * the full product experience (file tree, code preview, swagger,
 * download) works with no API key. The real generator (openai.ts)
 * returns the same GenerationResult shape.
 * ───────────────────────────────────────────────────────────── */

const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);
const plural = (s: string) =>
  s.endsWith("y") ? s.slice(0, -1) + "ies" : s.endsWith("s") ? s + "es" : s + "s";
const kebabPlural = (s: string) => plural(lower(s)).replace(/([A-Z])/g, "-$1").toLowerCase();

function isMongo(req: GenerateRequest) {
  return req.database === "mongodb" || req.schemaType === "mongoose";
}

/* ─── Shared infrastructure files ─── */

function packageJson(req: GenerateRequest, entities: SchemaEntity[]): string {
  const mongo = isMongo(req);
  const deps: Record<string, string> = {
    express: "^4.21.2",
    cors: "^2.8.5",
    helmet: "^8.0.0",
    morgan: "^1.10.0",
    dotenv: "^16.4.7",
    bcryptjs: "^2.4.3",
    jsonwebtoken: "^9.0.2",
    "express-rate-limit": "^7.4.1",
  };
  if (req.validation.zod) deps["zod"] = "^3.24.1";
  if (req.validation.joi) deps["joi"] = "^17.13.3";
  if (req.documentation.swagger) {
    deps["swagger-ui-express"] = "^5.0.1";
    deps["swagger-jsdoc"] = "^6.2.8";
  }
  if (mongo) deps["mongoose"] = "^8.9.3";
  else deps["@prisma/client"] = "^6.1.0";

  const devDeps: Record<string, string> = {
    typescript: "^5.7.2",
    "ts-node": "^10.9.2",
    "ts-node-dev": "^2.0.0",
    "@types/express": "^5.0.0",
    "@types/cors": "^2.8.17",
    "@types/morgan": "^1.9.9",
    "@types/bcryptjs": "^2.4.6",
    "@types/jsonwebtoken": "^9.0.7",
    "@types/node": "^22.10.2",
    jest: "^29.7.0",
    "ts-jest": "^29.2.5",
    "@types/jest": "^29.5.14",
    supertest: "^7.0.0",
    "@types/supertest": "^6.0.2",
  };
  if (!mongo) devDeps["prisma"] = "^6.1.0";

  const scripts: Record<string, string> = {
    dev: "ts-node-dev --respawn --transpile-only src/server.ts",
    build: "tsc -p tsconfig.json",
    start: "node dist/server.js",
    test: "jest --passWithNoTests",
    seed: "ts-node src/utils/seed.ts",
  };
  if (!mongo) {
    scripts["prisma:generate"] = "prisma generate";
    scripts["prisma:migrate"] = "prisma migrate dev";
  }

  return JSON.stringify(
    {
      name: "generated-backend",
      version: "1.0.0",
      description: `Backend generated by AI API Generator (${entities.length} entities)`,
      main: "dist/server.js",
      scripts,
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2
  );
}

function envExample(req: GenerateRequest): string {
  const dbUrl = isMongo(req)
    ? "DATABASE_URL=mongodb://localhost:27017/generated"
    : req.database === "sqlite"
      ? 'DATABASE_URL="file:./dev.db"'
      : req.database === "mysql"
        ? "DATABASE_URL=mysql://root:password@localhost:3306/generated"
        : "DATABASE_URL=postgresql://postgres:password@localhost:5432/generated?schema=public";
  return `NODE_ENV=development
PORT=4000
${dbUrl}
JWT_SECRET=replace-with-a-long-random-string
JWT_EXPIRES_IN=15m
${req.auth.refreshToken ? "JWT_REFRESH_SECRET=another-long-random-string\nJWT_REFRESH_EXPIRES_IN=14d\n" : ""}CORS_ORIGIN=*
`;
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "commonjs",
        moduleResolution: "node",
        rootDir: "src",
        outDir: "dist",
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        strict: true,
        skipLibCheck: true,
        resolveJsonModule: true,
      },
      include: ["src/**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  );
}

function serverTs(): string {
  return `import 'dotenv/config';
import { createApp } from './app';
import { env } from './config/env';
import { connectDatabase, disconnectDatabase } from './config/database';
import { logger } from './utils/logger';

async function bootstrap() {
  await connectDatabase();
  const app = createApp();
  const server = app.listen(env.PORT, () => {
    logger.info(\`🚀 Server running on http://localhost:\${env.PORT}\`);
    logger.info(\`📚 API docs available at http://localhost:\${env.PORT}/docs\`);
  });

  const shutdown = async (signal: string) => {
    logger.info(\`\${signal} received, shutting down gracefully...\`);
    server.close(async () => {
      await disconnectDatabase();
      process.exit(0);
    });
  };
  process.on('SIGINT', () => shutdown('SIGINT'));
  process.on('SIGTERM', () => shutdown('SIGTERM'));
}

bootstrap().catch((err) => {
  logger.error('Fatal startup error', err);
  process.exit(1);
});
`;
}

function appTs(req: GenerateRequest, entities: SchemaEntity[]): string {
  const swagger = req.documentation.swagger;
  return `import express, { Application } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
${swagger ? "import swaggerUi from 'swagger-ui-express';\nimport { swaggerSpec } from './docs/swagger';\n" : ""}import { env } from './config/env';
import { router } from './routes';
import { errorHandler } from './middleware/error.middleware';
import { notFound } from './middleware/notFound.middleware';

export function createApp(): Application {
  const app = express();

  app.use(helmet());
  app.use(cors({ origin: env.CORS_ORIGIN }));
  app.use(express.json({ limit: '1mb' }));
  app.use(express.urlencoded({ extended: true }));
  app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
  app.use(
    rateLimit({
      windowMs: 15 * 60 * 1000,
      max: 300,
      standardHeaders: true,
      legacyHeaders: false,
    })
  );

  app.get('/health', (_req, res) => res.json({ status: 'ok', uptime: process.uptime() }));
${swagger ? "  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));\n  app.get('/openapi.json', (_req, res) => res.json(swaggerSpec));\n" : ""}  app.use('/api/v1', router);

  app.use(notFound);
  app.use(errorHandler);
  return app;
}
`;
}

function envConfig(): string {
  return `import { z } from 'zod';

const schema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().default(4000),
  DATABASE_URL: z.string(),
  JWT_SECRET: z.string().min(10),
  JWT_EXPIRES_IN: z.string().default('15m'),
  JWT_REFRESH_SECRET: z.string().optional(),
  JWT_REFRESH_EXPIRES_IN: z.string().default('14d'),
  CORS_ORIGIN: z.string().default('*'),
});

export const env = schema.parse(process.env);
`;
}

function databaseConfig(req: GenerateRequest): string {
  if (isMongo(req)) {
    return `import mongoose from 'mongoose';
import { env } from './env';
import { logger } from '../utils/logger';

export async function connectDatabase() {
  await mongoose.connect(env.DATABASE_URL);
  logger.info('✅ MongoDB connected');
}

export async function disconnectDatabase() {
  await mongoose.disconnect();
}
`;
  }
  return `import { PrismaClient } from '@prisma/client';
import { logger } from '../utils/logger';

export const prisma = new PrismaClient();

export async function connectDatabase() {
  await prisma.$connect();
  logger.info('✅ Database connected via Prisma');
}

export async function disconnectDatabase() {
  await prisma.$disconnect();
}
`;
}

function loggerUtil(): string {
  return `/* Minimal structured logger. Swap for pino/winston in production. */
type Level = 'info' | 'warn' | 'error' | 'debug';

function log(level: Level, message: string, meta?: unknown) {
  const time = new Date().toISOString();
  const line = \`[\${time}] \${level.toUpperCase()} \${message}\`;
  if (meta !== undefined) console[level === 'debug' ? 'log' : level](line, meta);
  else console[level === 'debug' ? 'log' : level](line);
}

export const logger = {
  info: (m: string, meta?: unknown) => log('info', m, meta),
  warn: (m: string, meta?: unknown) => log('warn', m, meta),
  error: (m: string, meta?: unknown) => log('error', m, meta),
  debug: (m: string, meta?: unknown) => log('debug', m, meta),
};
`;
}

function apiErrorUtil(): string {
  return `export class ApiError extends Error {
  statusCode: number;
  details?: unknown;
  constructor(statusCode: number, message: string, details?: unknown) {
    super(message);
    this.statusCode = statusCode;
    this.details = details;
    Error.captureStackTrace(this, this.constructor);
  }
  static badRequest(msg = 'Bad request', details?: unknown) { return new ApiError(400, msg, details); }
  static unauthorized(msg = 'Unauthorized') { return new ApiError(401, msg); }
  static forbidden(msg = 'Forbidden') { return new ApiError(403, msg); }
  static notFound(msg = 'Not found') { return new ApiError(404, msg); }
  static conflict(msg = 'Conflict') { return new ApiError(409, msg); }
}
`;
}

function paginationUtil(): string {
  return `import { Request } from 'express';

export interface PageParams {
  page: number;
  limit: number;
  skip: number;
  sort: string;
  order: 'asc' | 'desc';
  search: string;
}

export function getPageParams(req: Request): PageParams {
  const page = Math.max(1, parseInt(String(req.query.page ?? '1'), 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(String(req.query.limit ?? '20'), 10) || 20));
  const sort = String(req.query.sort ?? 'createdAt');
  const order = String(req.query.order ?? 'desc') === 'asc' ? 'asc' : 'desc';
  const search = String(req.query.search ?? '').trim();
  return { page, limit, skip: (page - 1) * limit, sort, order, search };
}

export function buildMeta(total: number, p: PageParams) {
  return {
    total,
    page: p.page,
    limit: p.limit,
    totalPages: Math.ceil(total / p.limit) || 1,
  };
}
`;
}

function errorMiddleware(): string {
  return `import { Request, Response, NextFunction } from 'express';
import { ApiError } from '../utils/api-error';
import { logger } from '../utils/logger';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function errorHandler(err: unknown, _req: Request, res: Response, _next: NextFunction) {
  if (err instanceof ApiError) {
    return res.status(err.statusCode).json({
      success: false,
      message: err.message,
      details: err.details,
    });
  }
  logger.error('Unhandled error', err);
  return res.status(500).json({ success: false, message: 'Internal server error' });
}
`;
}

function notFoundMiddleware(): string {
  return `import { Request, Response } from 'express';

export function notFound(req: Request, res: Response) {
  res.status(404).json({ success: false, message: \`Route \${req.method} \${req.originalUrl} not found\` });
}
`;
}

function authMiddleware(): string {
  return `import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { env } from '../config/env';
import { ApiError } from '../utils/api-error';

export interface AuthedRequest extends Request {
  user?: { id: string; email: string };
}

export function authenticate(req: AuthedRequest, _res: Response, next: NextFunction) {
  const header = req.headers.authorization;
  if (!header?.startsWith('Bearer ')) {
    return next(ApiError.unauthorized('Missing or malformed Authorization header'));
  }
  try {
    const payload = jwt.verify(header.slice(7), env.JWT_SECRET) as { id: string; email: string };
    req.user = { id: payload.id, email: payload.email };
    next();
  } catch {
    next(ApiError.unauthorized('Invalid or expired token'));
  }
}
`;
}

/* ─── Auth module ─── */

function authService(req: GenerateRequest): string {
  const mongo = isMongo(req);
  const store = mongo ? "UserModel" : "prisma.user";
  return `import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { env } from '../config/env';
import { ApiError } from '../utils/api-error';
${mongo ? "import { UserModel } from '../models/user.model';" : "import { prisma } from '../config/database';"}

function signAccessToken(user: { id: string; email: string }) {
  return jwt.sign({ id: user.id, email: user.email }, env.JWT_SECRET, { expiresIn: env.JWT_EXPIRES_IN });
}
${req.auth.refreshToken ? `
function signRefreshToken(user: { id: string; email: string }) {
  return jwt.sign({ id: user.id, email: user.email }, env.JWT_REFRESH_SECRET ?? env.JWT_SECRET, { expiresIn: env.JWT_REFRESH_EXPIRES_IN });
}` : ""}

export const AuthService = {
  async register(input: { name: string; email: string; password: string }) {
    const existing = await ${mongo ? `${store}.findOne({ email: input.email })` : `${store}.findUnique({ where: { email: input.email } })`};
    if (existing) throw ApiError.conflict('Email already registered');
    const passwordHash = await bcrypt.hash(input.password, 10);
    const user = await ${mongo
      ? `${store}.create({ name: input.name, email: input.email, password: passwordHash })`
      : `${store}.create({ data: { name: input.name, email: input.email, password: passwordHash } })`};
    const id = String(${mongo ? "user._id" : "user.id"});
    return this.buildAuthResponse({ id, email: user.email, name: user.name });
  },

  async login(input: { email: string; password: string }) {
    const user = await ${mongo ? `${store}.findOne({ email: input.email })` : `${store}.findUnique({ where: { email: input.email } })`};
    if (!user) throw ApiError.unauthorized('Invalid credentials');
    const ok = await bcrypt.compare(input.password, user.password);
    if (!ok) throw ApiError.unauthorized('Invalid credentials');
    const id = String(${mongo ? "user._id" : "user.id"});
    return this.buildAuthResponse({ id, email: user.email, name: user.name });
  },
${req.auth.refreshToken ? `
  async refresh(token: string) {
    try {
      const payload = jwt.verify(token, env.JWT_REFRESH_SECRET ?? env.JWT_SECRET) as { id: string; email: string };
      return { accessToken: signAccessToken(payload), refreshToken: signRefreshToken(payload) };
    } catch {
      throw ApiError.unauthorized('Invalid refresh token');
    }
  },
` : ""}
  buildAuthResponse(user: { id: string; email: string; name: string }) {
    return {
      user: { id: user.id, email: user.email, name: user.name },
      accessToken: signAccessToken(user),${req.auth.refreshToken ? "\n      refreshToken: signRefreshToken(user)," : ""}
    };
  },
};
`;
}

function authController(req: GenerateRequest): string {
  return `import { Request, Response, NextFunction } from 'express';
import { AuthService } from '../services/auth.service';

export const AuthController = {
  async register(req: Request, res: Response, next: NextFunction) {
    try {
      const result = await AuthService.register(req.body);
      res.status(201).json({ success: true, data: result });
    } catch (e) { next(e); }
  },
  async login(req: Request, res: Response, next: NextFunction) {
    try {
      const result = await AuthService.login(req.body);
      res.json({ success: true, data: result });
    } catch (e) { next(e); }
  },${req.auth.refreshToken ? `
  async refresh(req: Request, res: Response, next: NextFunction) {
    try {
      const result = await AuthService.refresh(req.body.refreshToken);
      res.json({ success: true, data: result });
    } catch (e) { next(e); }
  },` : ""}
};
`;
}

function authRoutes(req: GenerateRequest): string {
  return `import { Router } from 'express';
import { AuthController } from '../controllers/auth.controller';
import { validate } from '../middleware/validate.middleware';
import { registerSchema, loginSchema${req.auth.refreshToken ? ", refreshSchema" : ""} } from '../validators/auth.validator';

export const authRouter = Router();

authRouter.post('/register', validate(registerSchema), AuthController.register);
authRouter.post('/login', validate(loginSchema), AuthController.login);${req.auth.refreshToken ? `
authRouter.post('/refresh', validate(refreshSchema), AuthController.refresh);` : ""}
`;
}

function validateMiddleware(): string {
  return `import { Request, Response, NextFunction } from 'express';
import { ZodSchema } from 'zod';
import { ApiError } from '../utils/api-error';

export function validate(schema: ZodSchema) {
  return (req: Request, _res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.body);
    if (!result.success) {
      return next(ApiError.badRequest('Validation failed', result.error.flatten().fieldErrors));
    }
    req.body = result.data;
    next();
  };
}
`;
}

function authValidator(req: GenerateRequest): string {
  return `import { z } from 'zod';

export const registerSchema = z.object({
  name: z.string().min(2),
  email: z.string().email(),
  password: z.string().min(6),
});

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});
${req.auth.refreshToken ? `
export const refreshSchema = z.object({
  refreshToken: z.string().min(10),
});` : ""}
`;
}

/* ─── Per-entity files ─── */

function entityModel(req: GenerateRequest, e: SchemaEntity): string {
  if (isMongo(req)) {
    const fields = e.fields
      .filter((f) => !["_id", "id"].includes(f.name))
      .map((f) => `  ${f.name}: { type: ${mongoType(f.type)} },`)
      .join("\n");
    return `import { Schema, model, Document } from 'mongoose';

export interface I${e.name} extends Document {
${e.fields.filter((f) => !["_id", "id"].includes(f.name)).map((f) => `  ${f.name}: ${tsType(f.type)};`).join("\n")}
  createdAt: Date;
  updatedAt: Date;
}

const ${e.name}Schema = new Schema<I${e.name}>(
  {
${fields || "    name: { type: String },"}
  },
  { timestamps: true }
);

export const ${e.name}Model = model<I${e.name}>('${e.name}', ${e.name}Schema);
`;
  }
  // Prisma-backed: model is declared in schema.prisma; export a typed helper.
  return `import { prisma } from '../config/database';

/**
 * ${e.name} data-access is provided by Prisma Client (see prisma/schema.prisma).
 * This thin wrapper centralises the delegate so services stay decoupled.
 */
export const ${lower(e.name)}Repository = prisma.${lower(e.name)};
`;
}

function mongoType(t: string): string {
  const x = t.toLowerCase();
  if (x.includes("number") || x.includes("int") || x.includes("float") || x.includes("decimal")) return "Number";
  if (x.includes("bool")) return "Boolean";
  if (x.includes("date")) return "Date";
  if (x.includes("objectid")) return "Schema.Types.ObjectId";
  return "String";
}

function tsType(t: string): string {
  const x = t.toLowerCase();
  if (x.includes("number") || x.includes("int") || x.includes("float") || x.includes("decimal")) return "number";
  if (x.includes("bool")) return "boolean";
  if (x.includes("date")) return "Date";
  return "string";
}

function entityService(req: GenerateRequest, e: SchemaEntity): string {
  const mongo = isMongo(req);
  const model = mongo ? `${e.name}Model` : `${lower(e.name)}Repository`;
  const imp = mongo
    ? `import { ${e.name}Model } from '../models/${lower(e.name)}.model';`
    : `import { ${lower(e.name)}Repository } from '../models/${lower(e.name)}.model';`;
  const searchField = e.fields.find((f) => tsType(f.type) === "string")?.name ?? "name";

  return `import { PageParams, buildMeta } from '../utils/pagination';
import { ApiError } from '../utils/api-error';
${imp}

export const ${e.name}Service = {
  async list(p: PageParams) {
${mongo
    ? `    const filter = p.search ? { ${searchField}: { $regex: p.search, $options: 'i' } } : {};
    const [items, total] = await Promise.all([
      ${model}.find(filter).sort({ [p.sort]: p.order === 'asc' ? 1 : -1 }).skip(p.skip).limit(p.limit),
      ${model}.countDocuments(filter),
    ]);`
    : `    const where = p.search ? { ${searchField}: { contains: p.search, mode: 'insensitive' as const } } : {};
    const [items, total] = await Promise.all([
      ${model}.findMany({ where, orderBy: { [p.sort]: p.order }, skip: p.skip, take: p.limit }),
      ${model}.count({ where }),
    ]);`}
    return { items, meta: buildMeta(total, p) };
  },

  async getById(id: string) {
    const item = await ${mongo ? `${model}.findById(id)` : `${model}.findUnique({ where: { id } })`};
    if (!item) throw ApiError.notFound('${e.name} not found');
    return item;
  },

  async create(data: Record<string, unknown>) {
    return ${mongo ? `${model}.create(data)` : `${model}.create({ data })`};
  },

  async update(id: string, data: Record<string, unknown>) {
    await this.getById(id);
    return ${mongo ? `${model}.findByIdAndUpdate(id, data, { new: true })` : `${model}.update({ where: { id }, data })`};
  },

  async remove(id: string) {
    await this.getById(id);
    return ${mongo ? `${model}.findByIdAndDelete(id)` : `${model}.delete({ where: { id } })`};
  },
};
`;
}

function entityController(e: SchemaEntity): string {
  return `import { Request, Response, NextFunction } from 'express';
import { ${e.name}Service } from '../services/${lower(e.name)}.service';
import { getPageParams } from '../utils/pagination';

export const ${e.name}Controller = {
  async list(req: Request, res: Response, next: NextFunction) {
    try {
      const { items, meta } = await ${e.name}Service.list(getPageParams(req));
      res.json({ success: true, data: items, meta });
    } catch (e) { next(e); }
  },
  async get(req: Request, res: Response, next: NextFunction) {
    try {
      const item = await ${e.name}Service.getById(req.params.id);
      res.json({ success: true, data: item });
    } catch (e) { next(e); }
  },
  async create(req: Request, res: Response, next: NextFunction) {
    try {
      const item = await ${e.name}Service.create(req.body);
      res.status(201).json({ success: true, data: item });
    } catch (e) { next(e); }
  },
  async update(req: Request, res: Response, next: NextFunction) {
    try {
      const item = await ${e.name}Service.update(req.params.id, req.body);
      res.json({ success: true, data: item });
    } catch (e) { next(e); }
  },
  async remove(req: Request, res: Response, next: NextFunction) {
    try {
      await ${e.name}Service.remove(req.params.id);
      res.status(204).send();
    } catch (e) { next(e); }
  },
};
`;
}

function entityValidator(e: SchemaEntity): string {
  const fields = e.fields
    .filter((f) => !["id", "_id", "createdAt", "updatedAt"].includes(f.name))
    .map((f) => {
      const t = tsType(f.type);
      const zt =
        t === "number" ? "z.number()" : t === "boolean" ? "z.boolean()" : t === "Date" ? "z.coerce.date()" : "z.string()";
      return `  ${f.name}: ${zt}.optional(),`;
    })
    .join("\n");
  return `import { z } from 'zod';

export const create${e.name}Schema = z.object({
${fields || "  name: z.string(),"}
});

export const update${e.name}Schema = create${e.name}Schema.partial();
`;
}

function entityRoutes(req: GenerateRequest, e: SchemaEntity): string {
  const guard = req.auth.jwt ? "authenticate, " : "";
  return `import { Router } from 'express';
import { ${e.name}Controller } from '../controllers/${lower(e.name)}.controller';
import { validate } from '../middleware/validate.middleware';
import { create${e.name}Schema, update${e.name}Schema } from '../validators/${lower(e.name)}.validator';
${req.auth.jwt ? "import { authenticate } from '../middleware/auth.middleware';\n" : ""}
export const ${lower(e.name)}Router = Router();

${lower(e.name)}Router.get('/', ${e.name}Controller.list);
${lower(e.name)}Router.get('/:id', ${e.name}Controller.get);
${lower(e.name)}Router.post('/', ${guard}validate(create${e.name}Schema), ${e.name}Controller.create);
${lower(e.name)}Router.put('/:id', ${guard}validate(update${e.name}Schema), ${e.name}Controller.update);
${lower(e.name)}Router.delete('/:id', ${guard}${e.name}Controller.remove);
`;
}

function routesIndex(req: GenerateRequest, entities: SchemaEntity[]): string {
  const imports = entities
    .map((e) => `import { ${lower(e.name)}Router } from './${lower(e.name)}.routes';`)
    .join("\n");
  const mounts = entities
    .map((e) => `router.use('/${kebabPlural(e.name)}', ${lower(e.name)}Router);`)
    .join("\n");
  return `import { Router } from 'express';
import { authRouter } from './auth.routes';
${imports}

export const router = Router();

router.use('/auth', authRouter);
${mounts}
`;
}

function entityTest(e: SchemaEntity): string {
  return `import request from 'supertest';
import { createApp } from '../src/app';

const app = createApp();

describe('${e.name} API', () => {
  it('GET /api/v1/${kebabPlural(e.name)} returns a paginated list', async () => {
    const res = await request(app).get('/api/v1/${kebabPlural(e.name)}');
    expect([200, 401]).toContain(res.status);
  });

  it('POST /api/v1/${kebabPlural(e.name)} validates the body', async () => {
    const res = await request(app).post('/api/v1/${kebabPlural(e.name)}').send({});
    expect([201, 400, 401]).toContain(res.status);
  });
});
`;
}

function prismaSchema(req: GenerateRequest, entities: SchemaEntity[]): string {
  const provider =
    req.database === "mysql" ? "mysql" : req.database === "sqlite" ? "sqlite" : "postgresql";
  const models = entities
    .map((e) => {
      const fields = e.fields
        .filter((f) => !["id", "createdAt", "updatedAt"].includes(f.name))
        .map((f) => `  ${f.name} ${prismaType(f.type)}`)
        .join("\n");
      return `model ${e.name} {
  id        String   @id @default(cuid())
${fields || "  name      String"}
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`;
    })
    .join("\n\n");
  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  name      String
  email     String   @unique
  password  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

${models}
`;
}

function prismaType(t: string): string {
  const x = t.toLowerCase();
  if (x.includes("number") || x.includes("int")) return "Int?";
  if (x.includes("float") || x.includes("decimal")) return "Float?";
  if (x.includes("bool")) return "Boolean?";
  if (x.includes("date")) return "DateTime?";
  return "String?";
}

function seedScript(req: GenerateRequest, entities: SchemaEntity[]): string {
  const mongo = isMongo(req);
  return `import 'dotenv/config';
import bcrypt from 'bcryptjs';
${mongo ? "import { connectDatabase, disconnectDatabase } from '../config/database';\nimport { UserModel } from '../models/user.model';" : "import { prisma } from '../config/database';"}
import { logger } from './logger';

async function seed() {
${mongo ? "  await connectDatabase();" : ""}
  const passwordHash = await bcrypt.hash('Password123!', 10);
  ${mongo
    ? `await UserModel.updateOne({ email: 'admin@example.com' }, { name: 'Admin', email: 'admin@example.com', password: passwordHash }, { upsert: true });`
    : `await prisma.user.upsert({ where: { email: 'admin@example.com' }, update: {}, create: { name: 'Admin', email: 'admin@example.com', password: passwordHash } });`}
  logger.info('🌱 Seed complete. Login with admin@example.com / Password123!');
${mongo ? "  await disconnectDatabase();" : "  await prisma.$disconnect();"}
}

seed().catch((e) => { logger.error('Seed failed', e); process.exit(1); });
`;
}

function swaggerConfig(req: GenerateRequest, endpoints: SwaggerEndpoint[]): string {
  return `import swaggerJSDoc from 'swagger-jsdoc';

export const swaggerSpec = swaggerJSDoc({
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'Generated Backend API',
      version: '1.0.0',
      description: 'REST API generated by AI API Generator.',
    },
    servers: [{ url: '/api/v1' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.ts'],
});
`;
}

function buildEndpoints(req: GenerateRequest, entities: SchemaEntity[]): SwaggerEndpoint[] {
  const eps: SwaggerEndpoint[] = [
    { method: "POST", path: "/api/v1/auth/register", summary: "Register a new user", auth: false, tag: "Auth" },
    { method: "POST", path: "/api/v1/auth/login", summary: "Login and receive tokens", auth: false, tag: "Auth" },
  ];
  if (req.auth.refreshToken)
    eps.push({ method: "POST", path: "/api/v1/auth/refresh", summary: "Refresh access token", auth: false, tag: "Auth" });
  for (const e of entities) {
    const base = `/api/v1/${kebabPlural(e.name)}`;
    eps.push(
      { method: "GET", path: base, summary: `List ${e.name} (paginated, searchable)`, auth: false, tag: e.name },
      { method: "GET", path: `${base}/:id`, summary: `Get a ${e.name} by id`, auth: false, tag: e.name },
      { method: "POST", path: base, summary: `Create a ${e.name}`, auth: req.auth.jwt, tag: e.name },
      { method: "PUT", path: `${base}/:id`, summary: `Update a ${e.name}`, auth: req.auth.jwt, tag: e.name },
      { method: "DELETE", path: `${base}/:id`, summary: `Delete a ${e.name}`, auth: req.auth.jwt, tag: e.name }
    );
  }
  return eps;
}

function readme(req: GenerateRequest, entities: SchemaEntity[]): string {
  return `# Generated Backend

Production-ready REST API generated by **AI API Generator**.

## Stack
- Node.js + Express + TypeScript
- ${isMongo(req) ? "MongoDB + Mongoose" : `Prisma ORM (${req.database})`}
- JWT authentication${req.auth.refreshToken ? " with refresh tokens" : ""}
- Zod validation, centralized error handling, rate limiting, Helmet, CORS
${req.documentation.swagger ? "- Swagger UI at `/docs`" : ""}

## Entities
${entities.map((e) => `- **${e.name}** — full CRUD at \`/api/v1/${kebabPlural(e.name)}\``).join("\n")}

## Getting started
\`\`\`bash
npm install
cp .env.example .env      # fill in DATABASE_URL and JWT_SECRET
${isMongo(req) ? "" : "npm run prisma:generate\nnpm run prisma:migrate\n"}npm run seed              # optional: creates admin@example.com / Password123!
npm run dev
\`\`\`

The server starts on \`http://localhost:4000\`.${req.documentation.swagger ? " API docs: `http://localhost:4000/docs`." : ""}

## Project structure
\`\`\`
src/
  config/       env + database connection
  controllers/  request handlers
  services/     business logic
  models/       data models
  routes/       route definitions
  middleware/   auth, validation, errors
  validators/   Zod request schemas
  utils/        logger, errors, pagination, seed
  docs/         swagger config
  app.ts        express app factory
  server.ts     bootstrap + graceful shutdown
tests/          jest + supertest templates
\`\`\`

## Auth flow
1. \`POST /api/v1/auth/register\` → returns \`{ user, accessToken${req.auth.refreshToken ? ", refreshToken" : ""} }\`
2. Send \`Authorization: Bearer <accessToken>\` on protected routes.
${req.auth.refreshToken ? "3. `POST /api/v1/auth/refresh` with `{ refreshToken }` to rotate the access token." : ""}
`;
}

/* ─── Assembler ─── */

export function generateMockProject(req: GenerateRequest): GenerationResult {
  const analysis: SchemaAnalysis = analyzeSchema(req.input, req.schemaType);
  // Guarantee a User entity exists for the auth module.
  let entities = analysis.entities.filter((e) => e.name.toLowerCase() !== "user");
  if (entities.length === 0) {
    entities = [
      {
        name: "Item",
        fields: [
          { name: "name", type: "String" },
          { name: "description", type: "String" },
          { name: "price", type: "Number" },
        ],
        primaryKey: "id",
        relations: [],
      },
    ];
  }
  entities = entities.slice(0, 8); // keep the demo output focused

  const mongo = isMongo(req);
  const endpoints = buildEndpoints(req, entities);
  const files: GeneratedFile[] = [];

  const add = (path: string, code: string) => files.push({ path, code });

  // Root
  add("package.json", packageJson(req, entities));
  add("tsconfig.json", tsconfig());
  add(".env.example", envExample(req));
  add("README.md", readme(req, entities));

  // Config
  add("src/config/env.ts", envConfig());
  add("src/config/database.ts", databaseConfig(req));

  // App
  add("src/server.ts", serverTs());
  add("src/app.ts", appTs(req, entities));

  // Utils
  add("src/utils/logger.ts", loggerUtil());
  add("src/utils/api-error.ts", apiErrorUtil());
  add("src/utils/pagination.ts", paginationUtil());
  add("src/utils/seed.ts", seedScript(req, entities));

  // Middleware
  add("src/middleware/error.middleware.ts", errorMiddleware());
  add("src/middleware/notFound.middleware.ts", notFoundMiddleware());
  add("src/middleware/validate.middleware.ts", validateMiddleware());
  if (req.auth.jwt) add("src/middleware/auth.middleware.ts", authMiddleware());

  // Auth module
  add("src/services/auth.service.ts", authService(req));
  add("src/controllers/auth.controller.ts", authController(req));
  add("src/routes/auth.routes.ts", authRoutes(req));
  add("src/validators/auth.validator.ts", authValidator(req));

  // User model
  if (mongo) {
    add(
      "src/models/user.model.ts",
      `import { Schema, model, Document } from 'mongoose';

export interface IUser extends Document {
  name: string;
  email: string;
  password: string;
}

const UserSchema = new Schema<IUser>(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
  },
  { timestamps: true }
);

export const UserModel = model<IUser>('User', UserSchema);
`
    );
  }

  // Per-entity files
  for (const e of entities) {
    add(`src/models/${lower(e.name)}.model.ts`, entityModel(req, e));
    add(`src/services/${lower(e.name)}.service.ts`, entityService(req, e));
    add(`src/controllers/${lower(e.name)}.controller.ts`, entityController(e));
    add(`src/validators/${lower(e.name)}.validator.ts`, entityValidator(e));
    add(`src/routes/${lower(e.name)}.routes.ts`, entityRoutes(req, e));
    add(`tests/${lower(e.name)}.test.ts`, entityTest(e));
  }

  add("src/routes/index.ts", routesIndex(req, entities));

  // Docs
  if (req.documentation.swagger) add("src/docs/swagger.ts", swaggerConfig(req, endpoints));

  // Prisma schema
  if (!mongo) add("prisma/schema.prisma", prismaSchema(req, entities));

  const architecture = `Layered ${req.framework} architecture: HTTP routes delegate to thin controllers, which call framework-agnostic services that own the business logic and talk to the ${
    mongo ? "Mongoose models" : "Prisma data layer"
  }. Cross-cutting concerns (auth, validation, errors, rate limiting) live in dedicated middleware, keeping each layer single-responsibility and independently testable.`;

  return {
    summary: `Generated a ${req.language} ${req.framework} backend for ${entities.length} entit${
      entities.length === 1 ? "y" : "ies"
    } (${entities.map((e) => e.name).join(", ")}) with ${
      req.auth.jwt ? "JWT auth" : "no auth"
    }${req.auth.refreshToken ? " + refresh tokens" : ""}, validation, pagination and ${
      req.documentation.swagger ? "Swagger docs" : "documented routes"
    }.`,
    architecture,
    analysis: { ...analysis, entities },
    files,
    endpoints,
    readme: readme(req, entities),
    explanation: buildExplanation(req, entities),
    meta: {
      model: "mock-generator",
      mock: true,
      generatedAt: new Date().toISOString(),
      options: extractOptions(req),
    },
  };
}

function extractOptions(req: GenerateRequest) {
  const { input, ...options } = req;
  void input;
  return options;
}

function buildExplanation(req: GenerateRequest, entities: SchemaEntity[]): string {
  return `## How this backend works

### Architecture
The project follows a clean, layered architecture — **routes → controllers → services → models**. Each layer has a single responsibility, which keeps the code testable and easy to extend.

### Authentication
${req.auth.jwt
    ? `Auth uses **JWT**. \`POST /auth/register\` hashes the password with **bcrypt** and returns a signed access token${req.auth.refreshToken ? " and a refresh token" : ""}. The \`authenticate\` middleware verifies the \`Authorization: Bearer\` header on protected write routes.`
    : "Authentication is disabled for this configuration."}

### Relationships
${entities.some((e) => e.relations && e.relations.length)
    ? entities
        .filter((e) => e.relations && e.relations.length)
        .map((e) => `- **${e.name}** relates to ${e.relations!.join(", ")}`)
        .join("\n")
    : "Entities are modelled independently; add foreign keys/refs to introduce relationships."}

### CRUD
Every entity exposes list (with **pagination, sorting, filtering and search**), get-by-id, create, update and delete endpoints, implemented consistently across controllers and services.

### Validation
Write endpoints run through a \`validate(schema)\` middleware backed by **Zod**, returning structured 400 errors with field-level messages.

### Middleware & API flow
A request flows through security headers (Helmet) → CORS → body parsing → logging → rate limiting → route → validation → controller → service → data layer, with a centralized error handler formatting every failure into a consistent JSON envelope.`;
}
